import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components/layout";
import { Toaster } from 'react-hot-toast';
import CartContextProvider from "@/contexts/cartContext";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ProviderContainer from "@/components/ProviderContainer/ProviderContainer";
import { WishlistProvider } from "@/contexts/whislistContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderContainer>
          <WishlistProvider>
          <Navbar/>
            {children}
            <Toaster/>
            <Footer/>
            </WishlistProvider>
        </ProviderContainer>
        {/* <Provider store={store}>
          <CartContextProvider>
            <Navbar/>
            {children}
            <Toaster/>
            <Footer/>
          </CartContextProvider>
        </Provider> */}
        
        
      </body>
    </html>
  );
}
